// This file is assumed to be generated by `supabase gen types typescript ...`
// and contains the full Database type definition.
// For brevity, only a conceptual structure is shown here.
// Ensure this file exists and is correctly populated in your project.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      politicians: {
        Row: {
          id: string
          name: string
          party_id: string | null
          created_at: string
          // ... other politician fields
        }
        Insert: {
          // ...
        }
        Update: {
          // ...
        }
      }
      political_parties: {
        Row: {
          id: string
          name: string
          // ... other party fields
        }
        Insert: {
          // ...
        }
        Update: {
          // ...
        }
      }
      // ... other tables
    }
    Views: {
      // ...
    }
    Functions: {
      // ...
    }
    Enums: {
      // ...
    }
    CompositeTypes: {
      // ...
    }
  }
}
