// This file should be generated by Supabase CLI: supabase gen types typescript --project-id <your-project-id> --schema public > types/supabase.ts
// For now, providing a minimal structure based on the schema.sql
// PLEASE REPLACE THIS WITH THE AUTO-GENERATED FILE.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      political_organizations: {
        Row: {
          id: string
          report_id: string
          name: string | null
          address: string | null
          representative_name: string | null
          accountant_name: string | null
          report_year: number | null
          raw_ocr_text: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          report_id: string
          name?: string | null
          address?: string | null
          representative_name?: string | null
          accountant_name?: string | null
          report_year?: number | null
          raw_ocr_text?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          report_id?: string
          name?: string | null
          address?: string | null
          representative_name?: string | null
          accountant_name?: string | null
          report_year?: number | null
          raw_ocr_text?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      financial_summaries: {
        Row: {
          id: string
          organization_report_id: string
          prev_year_balance: number | null
          current_year_revenue: number | null
          total_revenue: number | null
          total_expenditure: number | null
          next_year_balance: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_report_id: string
          prev_year_balance?: number | null
          current_year_revenue?: number | null
          total_revenue?: number | null
          total_expenditure?: number | null
          next_year_balance?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_report_id?: string
          prev_year_balance?: number | null
          current_year_revenue?: number | null
          total_revenue?: number | null
          total_expenditure?: number | null
          next_year_balance?: number | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "financial_summaries_organization_report_id_fkey"
            columns: ["organization_report_id"]
            referencedRelation: "political_organizations"
            referencedColumns: ["report_id"]
          },
        ]
      }
      revenue_details: {
        Row: {
          id: string
          organization_report_id: string
          category: string | null
          item_name: string | null
          amount: number | null
          donor_name: string | null
          donor_address: string | null
          donor_occupation: string | null
          donation_date: string | null // DATE
          remarks: string | null
          source_document_page: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_report_id: string
          category?: string | null
          item_name?: string | null
          amount?: number | null
          donor_name?: string | null
          donor_address?: string | null
          donor_occupation?: string | null
          donation_date?: string | null // DATE
          remarks?: string | null
          source_document_page?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_report_id?: string
          category?: string | null
          item_name?: string | null
          amount?: number | null
          donor_name?: string | null
          donor_address?: string | null
          donor_occupation?: string | null
          donation_date?: string | null // DATE
          remarks?: string | null
          source_document_page?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "revenue_details_organization_report_id_fkey"
            columns: ["organization_report_id"]
            referencedRelation: "political_organizations"
            referencedColumns: ["report_id"]
          },
        ]
      }
      expenditure_details: {
        Row: {
          id: string
          organization_report_id: string
          category: string | null
          item_name: string | null
          purpose: string | null
          amount: number | null
          expenditure_date: string | null // DATE
          payee_name: string | null
          payee_address: string | null
          remarks: string | null
          source_document_page: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_report_id: string
          category?: string | null
          item_name?: string | null
          purpose?: string | null
          amount?: number | null
          expenditure_date?: string | null // DATE
          payee_name?: string | null
          payee_address?: string | null
          remarks?: string | null
          source_document_page?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_report_id?: string
          category?: string | null
          item_name?: string | null
          purpose?: string | null
          amount?: number | null
          expenditure_date?: string | null // DATE
          payee_name?: string | null
          payee_address?: string | null
          remarks?: string | null
          source_document_page?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "expenditure_details_organization_report_id_fkey"
            columns: ["organization_report_id"]
            referencedRelation: "political_organizations"
            referencedColumns: ["report_id"]
          },
        ]
      }
      asset_details: {
        Row: {
          id: string
          organization_report_id: string
          asset_type: string | null
          description: string | null
          value: number | null
          acquisition_date: string | null // DATE
          remarks: string | null
          source_document_page: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_report_id: string
          asset_type?: string | null
          description?: string | null
          value?: number | null
          acquisition_date?: string | null // DATE
          remarks?: string | null
          source_document_page?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_report_id?: string
          asset_type?: string | null
          description?: string | null
          value?: number | null
          acquisition_date?: string | null // DATE
          remarks?: string | null
          source_document_page?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "asset_details_organization_report_id_fkey"
            columns: ["organization_report_id"]
            referencedRelation: "political_organizations"
            referencedColumns: ["report_id"]
          },
        ]
      }
      audit_documents: {
        Row: {
          id: string
          organization_report_id: string
          document_type: string | null
          has_document: boolean | null
          auditor_name: string | null
          audit_date: string | null // DATE
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_report_id: string
          document_type?: string | null
          has_document?: boolean | null
          auditor_name?: string | null
          audit_date?: string | null // DATE
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_report_id?: string
          document_type?: string | null
          has_document?: boolean | null
          auditor_name?: string | null
          audit_date?: string | null // DATE
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_documents_organization_report_id_fkey"
            columns: ["organization_report_id"]
            referencedRelation: "political_organizations"
            referencedColumns: ["report_id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Helper type for insert operations
export type TablesInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"]
// Helper type for row operations
export type TablesRow<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"]
